#!/usr/bin/php
<?php
require_once('bootstrap.php');

// TODO: Mutex

// Create the backup and let it figure the rest out
try
{
	$backup = new Omniabackup\Omniabackup();
	$backup->run();
}
catch(Exception $e)
{
	printf("Error: %s\nIn %s at line %d\n", $e->getMessage(), $e->getFile(), $e->getLine());
}