#!/usr/bin/php
<?php
// Includes
require_once('vendor/autoload.php');
include('src/OmniaBackup.php');

// TODO: Mutex

// Create the backup and let it figure the rest out
$backup = new Omniabackup();
$backup->run();