#!/usr/bin/php
<?php
// Incluse
include('lib/omniashell/omniashell.php');

// Create the shell
$shell = new Omniashell();

// Check basic arguments
if($argc <= 2 && @$argv[1] != 'help')
{
	$shell->help();
	die("Not enough arguments");
}

// The main interperter
$cmd = strtolower($argv[1]);
$user = strtolower($argv[2]);
@$project = ($argv[3] == '-P') ? strtolower($argv[4]) : null;
@$args = array_slice($argv, (($argv[3] == '-P') ? 5 : 3));

switch($cmd)
{
	case 'help':
		$shell->help();
	break;
	case 'devadd':
		$shell->devadd($user, $args);
	break;
	default:
		printf("Not a valid command, see help.");
}