#!/usr/bin/php
<?php
// Include
include('src/OmniaShell.php');

// Create the shell
$shell = new Omniashell();

// Check basic arguments
if($argc <= 1)
{
	$shell->help();
	die("Not enough arguments\n");
}

// The main interperter
$cmd = strtolower($argv[1]);
@$args = array_slice($argv, 2);

switch($cmd)
{
	case 'help':
		$shell->help();
	break;
	case 'devadd':
		$shell->devadd($args);
	break;
	case 'devdel':
		$shell->devdel($args);
	break;
	case 'projectadd':
		$shell->projectadd($args);
	break;
	case 'projectdel':
		$shell->projectdel($args);
	break;
	// Useless options
	case 'pass':
		$shell->pass();
	break;
	case 'passwd':
		$shell->passwd($args);
	break;
	default:
		printf("Not a valid command, see help.\n");
}