#!/usr/bin/php
<?php
// Incluse
include(__DIR__.'/lib/omniashell/omniabackup.php');

// TODO: We should make sure this script does not run more then once on the same minute

// Create the backup and let it figure the rest out
$backup = new Omniabackup();
$backup->run();